### ISSUE TITLE
Every yaml is ordered alphabetically 

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/app-services-cli#1500]
Ordering of yaml by keys.
```
kafka:
  bootstrapserverhost: kannan-ins-c--do--k-b-d-r-ig-ig.bf2.kafka.rhcloud.com:443
  failedreason: ""
  id: c91do42k8b3d6r1ig6ig
  name: kannan-instance
  status: ready
location: /home/rkpattnaik780/.config/rhoas/contexts.json
name: harari
registry:
  id: cc8a243a-feed-4a4c-9394-5a35ce83cca5
  name: prod
  registryurl: https://bu98.serviceregistry.rhcloud.com/t/cc8a243a-feed-4a4c-9394-5a35ce83cca5
  status: ready
```

_Originally posted by @rkpattnaik780 in https://github.com/redhat-developer/app-services-cli/issues/1498#issuecomment-1084216875_
