### ISSUE TITLE
"$rhoas cluster bind": --bind-env flag not taken into account

### ISSUE THREAD

**Issue by btison** [redhat-developer/app-services-cli#1665]
## Description

**Version**:  
0.46.1

When binding a kafka  or service registry instance to an application, the `bind-env` parameter has no effect.

### Steps to reproduce

* Deploy an application on OpenShift
* Provision a trial RHOSAK Kafka instance
* Connect the Kafka instance to the namespace
* Bind the application to the Kafka instance. Set the `bind-env` flag.
  ```
  $ rhoas cluster bind --app-name activity-tracking --bind-env --service-name globex --service-type kafka -n user1-globex -y
  ```

### Expected vs actual behaviour

Expected: a `ServiceBinding` CR with `bindAsFiles` set to `false`
```
apiVersion: binding.operators.coreos.com/v1alpha1
kind: ServiceBinding
[...]
spec:
  application:
    group: apps
    name: activity-tracking
    resource: deployments
    version: v1
  bindAsFiles: false
  services:
    - group: rhoas.redhat.com
      name: globex
      resource: kafkaconnections
      version: v1alpha1
status:
  conditions:
  [...]
  secret: globex-1c82-3e4fe97f
```
Actual: a `ServiceBinding` CR with `bindAsFiles` set to `true`
```
apiVersion: binding.operators.coreos.com/v1alpha1
kind: ServiceBinding
[...]
spec:
  application:
    group: apps
    name: activity-tracking
    resource: deployments
    version: v1
  bindAsFiles: true
  services:
    - group: rhoas.redhat.com
      name: globex
      resource: kafkaconnections
      version: v1alpha1
status:
  conditions:
  [...]
  secret: globex-1c82-3e4fe97f
```
