### ISSUE TITLE
CLI should use operator MKC object for status and watch for it

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/app-services-cli#337]
Status requires separate subresource `/status` for updates.
However normal users might not have permissions for updating status and status updates will clash with the.

Format done by operator:
```
spec:
  accessTokenSecretName: rh-managed-services-api-accesstoken
  credentials:
    serviceAccountSecretName: rh-managed-services-service-account
  kafkaId: 1oI6vmySzEXjZpJrrMoeOzssCIb
status:
  boostrapServer:
    host: 'evan-test--oi-vmyszexjzpjrrmoeozsscib.kafka.devshift.org:443'
  message: Created
  saslMechanism: PLAIN
  securityProtocol: SSL
  serviceAccountSecretName: rh-managed-services-service-account
  updated: '2021-02-11T12:41:58.016741Z'
```

CLI cannot post status and make resource functional. We would also need to somehow disable processing of those resource etc.

Requires investigation
