### ISSUE TITLE
Erroneous file content while resetting service account credentials with kubernetes-secret as the file format

### ISSUE THREAD

**Issue by rkpattnaik780** [redhat-developer/app-services-cli#508]
## Description

**Version**: 0.20.2-2-g44738ee

### Steps to reproduce

1. Reset credentials of a service account with `kubernetes-secret` as the file format.
```
go run ./cmd/rhoas serviceaccount reset-credentials --id <service account id> --file-format kubernetes-secret
```

### Expected vs actual behaviour

Currently the credentials are saved in `cli/credentials.yaml` with the content:
```
%!(EXTRA string=<service account id>, string=<password>)
```

Whereas it should look something like:

```
kind: Secret
apiVersion: v1
metadata:
  name: "rhoas-service-account-secret"
stringData:
  clientID: "<service account client id>"
  clientSecret: "<service account secret>"
type: Opaque
```
